# Generated by Django 2.0.5 on 2018-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=30)),
                ('Service', models.CharField(choices=[('Оценка активов', 'Оценка активов'), ('Бизнес планирование', 'Бизнес планирование'), ('Стратегический консалтинг', 'Стратегический консалтинг'), ('Анализ банков', 'Анализ банков'), ('Маркетинговые исследования', 'Маркетинговые исследования')], max_length=100)),
            ],
        ),
    ]
